export const ruLang = {
    SITE_NAME: 'Мой магазинчик',
    HELLO_GUEST:' Здравствуйте, Гость!',
    YOU_LOGIN_AS: 'Вы вошли как: ',
    MENU_CATEGORY: 'Категории',
    MENU_PRODUCT: 'Продукты',
    MENU_DELIVERY: 'Доставка',
    MENU_EXIT: 'Выход',
    MENU_LOGIN: 'Войти',

    SELECT_IMAGE_FOR_PREVIEW: 'Загрузите картинку, для предпросмотра',
    UPLOAD_IMAGE: 'Загрузить',
    TABLE_NAME: 'Имя',
    TABLE_DESCRIPTION: 'Описание',

    TABLE_EMPTY_DATA_SOURCE_MESSAGE: 'Нет элементов для отображения',
    TABLE_ADD_TOOLTIP: 'Добавить',
    TABLE_DELETE_TOOLTIP: 'Удалить',
    TABLE_EDIT_TOOLTIP: 'Изменить',

    TABLE_FILTER_ROW_TOOLTIP: 'Фильтр',
    TABLE_EDIT_ROW_DELETE_TEXT: 'Вы действительно хотите удалить этот элемент?',
    TABLE_EDIT_ROW_CANCEL_TOOLTIP: 'Отмена',
    TABLE_EDIT_ROW_SAVE_TOOLTIP: 'Применить',

    TABLE_PLACEHOLDER: 'Перетяните заголовки ...',
    TABLE_ACTIONS: 'Действия',

    TABLE_LABEL_DISPLAYED_ROWS: '{from}-{to} всего: {count}',
    TABLE_LABEL_ROWS_SELECT: 'строк(и)',
    TABLE_LABELROWS_PER_PAGE: 'Строк на страницу:',
    TABLE_FIRST_ARIA_LABEL: 'Первая',
    TABLE_FIRST_TOOLTIP: 'Первая',
    TABLE_PREVIOUS_AREA_LABEL: 'Предыдущая',
    TABLE_PREVIOUS_TOOLTIP: 'Предыдущая',
    TABLE_NEXT_ARIA_LABEL: 'Следующая',
    TABLE_NEXT_TOOLTIP: 'Следующая',
    TABLE_LAST_AREA_LABEL: 'Последняя',
    TABLE_LAST_TOOLTIP: 'Последняя',

    TABLE_ADD_REMOVE_COLUMNS: 'Добавить или удалить столбцы',
    TABLE_ROWS_SELECTED: '{0} строк выбрано',
    TABLE_SHOW_COLUMNS_TITLE: 'Отобразить столбцы',
    TABLE_SHOW_COLUMNS_ARIA_LABEL: 'Отобразить столбцы',
    TABLE_EXPORT_TITLE: 'Экспорт',
    TABLE_EXPORT_ARIA_LABEL: 'Экспорт',
    TABLE_EXPORT_NAME: 'Выгрузить как CSV',
    TABLE_SEARCH_TOOLTIP: 'Поиск',
    TABLE_SEARCH_PLACEHOLDER: 'Поиск',

    TITLE_CATEGORIES: 'Категории',
    TITLE_PRODUCTS: 'Товары',
    TITLE_DEPARTMENTS: 'Разделы',
    LINK_CATEGORIES: 'категории',
    LINK_PRODUCTS: 'товары',
    LINK_DEPARTMENTS: 'разделы',

};
